name: envision  CI/CD Pipeline

on:
  push:
    branches:
      - main # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and Test
        run: npm test

      - name: Deploy to Server
        run: |
          # Add your deployment script here
          # For example: npm run deploy


